# Generated by Django 4.0.4 on 2022-05-11 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prénom', models.CharField(max_length=255)),
                ('ddn', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('Password', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agence', models.CharField(max_length=255)),
                ('siége_agence', models.TextField()),
                ('Num_contact', models.TextField()),
                ('email_agence', models.EmailField(max_length=254, unique=True)),
                ('Nmbr_succursales', models.PositiveIntegerField()),
                ('nmbr_flotte', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Code_Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('pourcentage', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Demanade_Partenariat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prop', models.CharField(max_length=255)),
                ('prénom_prop', models.CharField(max_length=255)),
                ('ddn_prop', models.DateField()),
                ('email_prop', models.EmailField(max_length=254, unique=True)),
                ('phone_prop', models.CharField(max_length=255)),
                ('Password', models.TextField()),
                ('nom_agence', models.CharField(max_length=255)),
                ('siége_agence', models.TextField()),
                ('Num_contact', models.TextField()),
                ('email_agence', models.EmailField(max_length=254, unique=True)),
                ('Nmbr_succursales', models.PositiveIntegerField()),
                ('nmbr_flotte', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Demande_Compte_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_admin', models.CharField(max_length=255)),
                ('prénom_admin', models.CharField(max_length=255)),
                ('ddn_admin', models.DateField()),
                ('email_admin', models.EmailField(max_length=254, unique=True)),
                ('phone_admin', models.CharField(max_length=255)),
                ('Password_admin', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dépot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_dpt', models.TextField()),
                ('capacité_dpt', models.PositiveIntegerField()),
                ('id_agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientSide.agence')),
            ],
        ),
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prénom', models.CharField(max_length=255)),
                ('ddn', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('Password', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Propriétaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prénom', models.CharField(max_length=255)),
                ('ddn', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('Password', models.TextField()),
                ('id_agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientSide.agence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Véhicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.PositiveIntegerField(unique=True)),
                ('prix_heure', models.FloatField()),
                ('prix_jour', models.FloatField()),
                ('description', models.TextField()),
                ('etat_véhicule', models.CharField(choices=[('intrusion', 'intrusion'), ('enPanne', 'enPanne'), ('prochainementDisponible', 'prochainementDisponible'), ('enMarche', 'enMarche'), ('enArret', 'enArret')], default='enMarche', max_length=255)),
                ('disponibilité', models.BooleanField()),
                ('catégorie_véhicule', models.CharField(choices=[('Petites', 'Petites'), ('Moyennes', 'Moyennes'), ('Larges', 'Larges'), ('Premium', 'Premium'), ('Monospaces', 'Monospaces'), ('SUV', 'SUV')], max_length=255)),
                ('id_dépot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientSide.dépot')),
            ],
        ),
        migrations.CreateModel(
            name='Secrétaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prénom', models.CharField(max_length=255)),
                ('ddn', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('Password', models.TextField()),
                ('id_agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientSide.agence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Réservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_début', models.DateField()),
                ('date_fin', models.DateField()),
                ('heure_début', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('id_locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientSide.locataire')),
            ],
        ),
        migrations.CreateModel(
            name='Réclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_réclamation', models.TextField()),
                ('id_locatairec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientSide.locataire')),
                ('id_propriétaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientSide.propriétaire')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('id_locatairec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientSide.locataire')),
            ],
        ),
        migrations.CreateModel(
            name='Garagiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prénom', models.CharField(max_length=255)),
                ('ddn', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('Password', models.TextField()),
                ('id_agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientSide.agence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_Original', models.FloatField()),
                ('prix_total', models.FloatField()),
                ('id_réservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientSide.réservation')),
            ],
        ),
        migrations.CreateModel(
            name='Contrat_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_réservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientSide.réservation')),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('id_agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientSide.agence')),
                ('id_locatairec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientSide.locataire')),
            ],
        ),
        migrations.CreateModel(
            name='Admin_agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prénom', models.CharField(max_length=255)),
                ('ddn', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('Password', models.TextField()),
                ('id_agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientSide.agence')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
