# Generated by Django 4.0.4 on 2022-05-23 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientSide', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agence',
            old_name='nmbr_flotte',
            new_name='Nmbr_flotte',
        ),
        migrations.RenameField(
            model_name='code_promo',
            old_name='code',
            new_name='code_promo',
        ),
        migrations.RemoveField(
            model_name='réclamation',
            name='id_propriétaire',
        ),
        migrations.AddField(
            model_name='code_promo',
            name='id_véhicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientSide.véhicule'),
        ),
        migrations.AddField(
            model_name='demanade_partenariat',
            name='id_administrateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientSide.administrateur'),
        ),
        migrations.AddField(
            model_name='demande_compte_admin',
            name='id_administrateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientSide.administrateur'),
        ),
        migrations.AddField(
            model_name='demande_compte_admin',
            name='id_agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientSide.agence'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='id_agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientSide.agence'),
        ),
        migrations.AddField(
            model_name='réclamation',
            name='id_agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientSide.agence'),
        ),
        migrations.AddField(
            model_name='réservation',
            name='id_véhicule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientSide.véhicule'),
        ),
        migrations.AddField(
            model_name='véhicule',
            name='marque',
            field=models.CharField(default='ll', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='véhicule',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admin_agence',
            name='id_agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientSide.agence'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='id_locatairec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientSide.locataire'),
        ),
        migrations.AlterField(
            model_name='dépot',
            name='id_agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientSide.agence'),
        ),
        migrations.AlterField(
            model_name='garagiste',
            name='id_agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientSide.agence'),
        ),
        migrations.AlterField(
            model_name='propriétaire',
            name='id_agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientSide.agence'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='id_locatairec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientSide.locataire'),
        ),
        migrations.AlterField(
            model_name='réclamation',
            name='id_locatairec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientSide.locataire'),
        ),
        migrations.AlterField(
            model_name='réservation',
            name='id_locataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientSide.locataire'),
        ),
        migrations.AlterField(
            model_name='secrétaire',
            name='id_agence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientSide.agence'),
        ),
        migrations.AlterField(
            model_name='véhicule',
            name='id_dépot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clientSide.dépot'),
        ),
        migrations.AlterField(
            model_name='véhicule',
            name='matricule',
            field=models.PositiveIntegerField(default='ll', unique=True),
        ),
    ]
