# Generated by Django 4.0.4 on 2022-05-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientSide', '0002_rename_nmbr_flotte_agence_nmbr_flotte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='logo_agence',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='demanade_partenariat',
            name='logo_agence',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='véhicule',
            name='img_vhl',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
