# Generated by Django 4.0.4 on 2022-05-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientSide', '0003_agence_logo_agence_demanade_partenariat_logo_agence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='véhicule',
            name='etat_véhicule',
            field=models.CharField(choices=[('intrusion', 'intrusion'), ('enPanne', 'en Panne'), ('prochainementDisponible', 'prochainement Disponible'), ('enMarche', 'en Marche'), ('enArret', 'en Arret')], default='enMarche', max_length=255),
        ),
    ]
