# Generated by Django 4.0.4 on 2022-05-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientSide', '0004_alter_véhicule_etat_véhicule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_agence',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='administrateur',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='agence',
            old_name='Nmbr_flotte',
            new_name='nmbr_flotte',
        ),
        migrations.RenameField(
            model_name='agence',
            old_name='Nmbr_succursales',
            new_name='nmbr_succursales',
        ),
        migrations.RenameField(
            model_name='agence',
            old_name='Num_contact',
            new_name='num_contact',
        ),
        migrations.RenameField(
            model_name='garagiste',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='locataire',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='propriétaire',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='secrétaire',
            old_name='Password',
            new_name='password',
        ),
    ]
